AppBundle\Entity\Room:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\RoomRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '20'
        floor:
            type: integer
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        reservations:
            targetEntity: Reservation
            mappedBy: room
